namespace Runefall.Presentation.Network
{
    /// <summary>
    /// Immutable data container holding information about the current Lobby and Relay session.
    /// Used to pass clean connection structures between LobbyRelayService and MultiplayerManager.
    /// </summary>
    public struct LobbyConnectionData
    {
        /// <summary>
        /// Unique identification string of the Unity Lobby in the UGS cloud.
        /// </summary>
        public string LobbyId { get; }

        /// <summary>
        /// The short 6-character room Join Code generated by Unity Relay.
        /// </summary>
        public string JoinCode { get; }

        /// <summary>
        /// True if this client created the session and is acting as the Host (Server + Client).
        /// </summary>
        public bool IsHost { get; }

        public LobbyConnectionData(string lobbyId, string joinCode, bool isHost)
        {
            LobbyId = lobbyId;
            JoinCode = joinCode;
            IsHost = isHost;
        }
    }
}
